---
title: "Rapport exercice 1 de STIC I - Camille Pellaton"
subtitle: "Document d'accompagnement des activités sur l'identité digitale"
lang: fr
date: last-modified
author:
  name: Camille Pellaton
  # orcid: 0000-0002-1825-0097
  url: https://tecfaetu.unige.ch/perso/maltt/pellato3/

format:
  html:
    theme: Superhero # Voir https://quarto.org/docs/output-formats/html-themes.html pour les options
    css: style.css 
    fontsize: 1.2rem
    linestretch: 1.4
    toc: true
    toc-location: left
    number-sections: true
    title-block-banner: true
    smooth-scroll: true
    anchor-sections: false
    link-external-icon: true
    embed-resources: true
---

## Liens

-   une [page web personnelle](https://tecfaetu.unige.ch/perso/maltt/pellato3/)
-   une [page personnelle sur EdutechWiki](https://edutechwiki.unige.ch/fr/Utilisateur:Camille_Pellaton#Int%C3%A9r%C3%AAts)
-   une [page travaux](http://tecfaetu.unige.ch/etu-maltt/drakkar/pellato3/)
-   Mise à jour de mes profils [ResearchGate](https://www.researchgate.net/profile/Camille-Pellaton-2) et [Github](https://github.com/camouie)

## Objectifs

L'objectif des différentes tâches réalisées est de mettre à jour et de soigner son identité digitale. Il s'agit également de créer des espaces web personnels au sein du MALTT afin de recenser et partager nos créations.

## Design

J'ai voulu faire un design minimaliste pour ma page personnelle et la page des travaux. Concernant ma page personnelle, j'ai porté une attention particulière aux polices utilisées (Google Fonts) pour le logo et le texte. Afin d'ajouter une touche de convivialité, j'ai utilisé des emojis dans le message d'accueil.

Concernant la page travaux, j'ai surtout porté mon attention sur la palette de couleur et, pour plus de lisibilié, j'ai démarqué le contenu d'un exercice par l'utilisation d'une "card".

## Production

Pour la création de ma page personnelle, j'ai commencé par réaliser un sketch papier du layout que je souhaitais. Pour m'inspirer pour la création des différentes sections, j'ai consulté les pages personnelles créées par la volée Concordia. Comme cela faisait longtemps que je n'avais plus créé de page web sans utiliser de Framework, j'ai décidé de le faire ici. Le HTML et le CSS ont été validés.

Ma page personnelle sur le wiki est très simple pour l'instant. Je ne voulais pas trop de redondance entre les différentes pages créées dans cet exercice, alors j'ai mis des liens lorsque cela était possible.

Pour mes différents comptes sociaux, j'ai contrôlé et mis à jour mes données personnelles, mes domaines d'intérets et les mots-clés utilisés, j'ai également vérifié le contenu public (Github). J'ai choisi des photos différentes pour ces deux comptes au vu de leur portée.

## Auto-évaluation

Les objectifs me semblent atteints. Toutefois, lors d'une prochaine itération, j'aimerais améliorer le design de ma page travaux et rendre mes pages responsives. J'aimerais aussi avoir une meilleure photo professionnelle pour mes comptes sociaux et ma page personnelle. Sur ma page wiki, j'aimerais ajouter plus de détails sur mes projets professionnels (rôle, thématique...)

## Bibliographie

-   [W3school](https://www.w3schools.com/css/)

## Ressources

-   [Google Fonts](https://fonts.google.com/) ( et [Noto Color Emoji](https://fonts.google.com/noto/specimen/Noto+Color+Emoji))

-   [Coloors](https://coolors.co/) (palettes de couleur)

-   [Fontawesome](https://fontawesome.com/icons) (icons réseaux sociaux)

-   [svgrepo](https://www.svgrepo.com/svg/2844/binary-code-numbers-on-monitor-screen) (image wiki)

-   Validation [HTML](https://validator.w3.org/) et [CSS](https://jigsaw.w3.org/css-validator/#validate_by_uri+with_options)